rootstock: better error treatment for genext2fs
As genext2fs eats lots of memory, it's normal to give an error if the user doesn't have enough memory, so we should give the correct error message for the user.

diff --git a/rootstock b/rootstock
--- a/rootstock
+++ b/rootstock
@@ -229,7 +229,10 @@ create_rootfs_image()
 {
     # create the ext3 image to be used later with qemu
     [ $QUIET ] || echo "I: Creating ext3 Image from the rootfs"
-    genext2fs -b $IMAGESIZE -i $BYTEINODE -d $ROOTFS $IMAGENAME >>$LOG 2>&1
+    if ! ERROR=$(genext2fs -b $IMAGESIZE -i $BYTEINODE -d $ROOTFS $IMAGENAME 2>&1);then
+        echo "E: $ERROR" | tee -a $LOG
+        cleanup
+    fi
     tune2fs -j $IMAGENAME >>$LOG 2>&1
     # fsck is expected to return != 0
     ! fsck.ext3 -y -f $IMAGENAME >>$LOG 2>&1
